repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-executables-have-shebangs
    -   id: check-shebang-scripts-are-executable
    -   id: check-merge-conflict
-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.83.2"
    hooks:
    -   id: terraform_fmt
    -   id: terraform_tflint
    -   id: terraform_validate
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.36.0
  hooks:
  - id: markdownlint-fix
  - id: markdownlint
