name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: setup checkout
      uses: actions/checkout@v3
    - name: setup setup-python
      uses: actions/setup-python@v3
    - name: setup tflint
      uses: terraform-linters/setup-tflint@v3
    - name: setup tfsec
      uses: aquasecurity/tfsec-action@v1.0.0
    - name: run pre-commit
      uses: pre-commit/action@v3.0.0
